baseURL: "https://joaocarlos.github.io"
title: Thiago C. Jesus
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
    pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Bio
          url: about/
          weight: 1
        - name: Projects
          url: projects/
          weight: 5
        - name: Publications
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Supervision
          url: supervision/
          weight: 4

params:
    description: "This website hosts João Carlos N. Bittencourt academic profile."
    author: João Carlos N. Bittencourt
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications", "teaching", "supervision"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Prof. Thiago C. Jesus, PhD
        position: "Assistant Professor, Center of Exact Sciences and Technology<br>Federal University of Recôncavo da Bahia, Brazil"
        intro: "I am a professor at the Center of Exact Sciences and Technology ([<u>CETEC</u>](https://ufrb.edu.br/cetec/)) at the Federal University of Recôncavo of Bahia ([<u>UFRB</u>](https://ufrb.edu.br/)). I teach in the Undergraduate Programs of Computer Engineering ([<u>ECP</u>](https://ufrb.edu.br/portal/index.php?option=com_chronoforms5&chronoform=ver-graduacao&id=19)), Electrical Engineering ([<u>EELE</u>](https://www.ufrb.edu.br/cetec/engenharia-eletrica)), and Exact Sciences and Technology ([<u>BCET</u>](https://www2.ufrb.edu.br/bcet/)). <br><br>My research includes Smart Cities, the Internet of Things, Embedded Systems, and Reconfigurable Hardware Accelerators."
        imageUrl: "picture.jpeg"
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: Bio
              url: about/
            - name: Projects
              url: projects/
            - name: Publications
              url: papers/
            - name: Books
              url: books/
            - name: Teaching
              url: teaching/
            - name: Supervision
              url: supervision/

    socialIcons:
        # - name: CV
        #   url: cv.pdf
        - name: Email
          url: mailto:joaocarlos@ufrb.edu.br
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=hEPWRnoAAAAJ
        - name: ORCID
          url: https://orcid.org/0000-0002-4540-512X
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Joao-Carlos-Bittencourt
        - name: Scopus
          url: https://www.scopus.com/authid/detail.uri?authorId=57117498600
        - name: Lattes
          url: https://lattes.cnpq.br/6741995694783822
        - name: GitHub
          url: https://github.com/joaocarlos
        - name: YouTube
          url: https://www.youtube.com/@joaocarlosbittencourt

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "João Carlos N. Bittencourt"
        icon: favicon.png
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
