baseURL: "https://tcjesus.github.io"
title: Thiago C. Jesus
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
    pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Bio
          url: about/
          weight: 1
        - name: Projects
          url: projects/
          weight: 5
        - name: Publications
          url: papers/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 3
        - name: Supervision
          url: supervision/
          weight: 4

params:
    description: "This website hosts Prof. Thiago C. Jesus academic profile."
    author: Thiago C. Jesus
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications", "teaching", "supervision"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Prof. Thiago C. Jesus, PhD
        position: "&sup1;Researcher, SYSTEC-ARISE, Faculty of Engineering, University of Porto, Porto, Portugal<br>&sup2;Associate Professor, Technology Department of State University of Feira de Santana, Feira de Santana, Brazil"
        intro: "I am a Researcher at [<u>SYSTEC</u>](https://systec.fe.up.pt/)–[<u>ARISE</u>](https://arise-la.pt/) at the Faculty of Engineering, University of Porto ([<u>FEUP</u>](https://www.up.pt/feup/en/)) in Porto, Portugal, and an Associate Professor in the Technology Department ([<u>DTEC</u>](https://www.dtec.uefs.br/)) at the State University of Feira de Santana, ([<u>UEFS</u>](https://www.uefs.br/)) in Feira de Santana, Brazil. <br><br>My research includes Smart Cities, the Internet of Things, Wireless (Visual) Sensor Networks, Embedded & Digital Systems, and Energy Management Systems."
        #imageUrl: "picture.jpeg"
        #imageUrl: "bio02.jpg"
        imageUrl: "bio02.png"
        imageWidth: 160
        imageHeight: 160
        buttons:
            - name: Bio
              url: about/
            - name: Projects
              url: projects/
            - name: Publications
              url: papers/
            #- name: Books
            #  url: books/
            - name: Teaching
              url: teaching/
            - name: Supervision
              url: supervision/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:jesus@fe.up.pt
        - name: Location
          url: location
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=3psJAQoAAAAJ
        - name: ORCID
          url: http://orcid.org/0000-0001-5299-6856
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Thiago-Jesus-5
        - name: Scopus
          url: https://www.scopus.com/authid/detail.uri?authorId=57212909335
        - name: Lattes
          url: http://lattes.cnpq.br/1846614285668988
        - name: GitHub
          url: https://github.com/tcjesus
        - name: YouTube
          url: https://www.youtube.com/@thiagocjesus

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
        text: "Thiago C. Jesus"
        icon: favicon.png
        iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
